from setuptools import setup, find_namespace_packages

scm_version_template = """# Generated by setuptools_scm
__all__ = ["__version__"]

__version__ = "{version}"
"""

setup(
    name="ts_observatory_model",
    description="Observatory Model.",
    use_scm_version={
        "write_to": "python/lsst/ts/observatory/model/version.py",
        "write_to_template": scm_version_template,
    },
    package_dir={"": "python"},
    packages=find_namespace_packages(where="python"),
    package_data={"": ["*.yaml", "*.conf"]},
    license="GPL",
    project_urls={
        "Bug Tracker": "https://jira.lsstcorp.org/secure/Dashboard.jspa",
        "Source Code": "https://github.com/lsst-ts/ts_observatory_model",
    },
)
