{% set data= load_setup_py_data() %}
package:
  name: "ts-observatory-model"
  version: {{ data.get('version') }}

source:
  path: ../

build:
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

test:
  requires:
    - ts-conda-build =0.3
    - ts-dateloc
  source_files:
    - python
    - tests
    - setup.cfg
  commands:
    - py.test -vs

requirements:
  host:
    - python
    - pip
    - setuptools_scm
    - setuptools
    - pytest-runner
  run:
    - python
    - setuptools
    - setuptools_scm
    - ts-dateloc
